name: flutter_apns_x
description: Demonstrates how to use the flutter_apnsX plugin.
publish_to: https://pub.dartlang.org
version: 0.0.1
homepage: https://github.com/Money1998/custom_apnsX.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  path_provider:
  flutter_local_notifications:
  plugin_platform_interface: ^2.1.3
  firebase_core: ^2.6.0
  firebase_messaging: ^14.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
